### ISSUE TITLE
Drop react-native-swiper fork dependency

### ISSUE THREAD

**Issue by machour** [Ernoff/rn-app-intro#1]
Hey @Ernoff, I was going through https://github.com/gitpoint/git-point/issues/396 and found out we replaced the old app intro module with yours.

I tried to upgrade to react native 0.49 to see the new features, but this seems impossible due to one of your dependencies still using react.PropTypes : https://github.com/FuYaoDe/react-native-swiper/blob/master/src/index.js#L109

The fork have not changed in a year, and https://github.com/leecade/react-native-swiper seems to have evolved & to be React 0.16 compatible.

Could you consider switching back to the original package?

**Comment by Ernoff** [comment]
Hey @machour Thanks for reaching out.

Dropping FuyaoDe's repo and using leecade's updated repo should fix this right??

Warm regards

**Comment by machour** [comment]
Hi,

I was taking about the fork of the swiper being outdated, not rn-app-intro
itself.
I had a problem while trying to run GitPoint on RN 0.49, as this dependency
uses PropTypes from React, not 'prop-types'

**Comment by Ernoff** [comment]
Yeah I quickly realized that! I will change to swiper's fork to the recommended one.

Thanks for pointing it out to me

**Comment by Ernoff** [comment]
Update has been done and published. Review and let me know

**Comment by machour** [comment]
That may have been a little to quick I'm afraid. A lot seems to have changed in react-native-swipper in the last year ;)

Now the app intro looks like this
![screen shot 2017-10-09 at 11 43 47 pm](https://user-images.githubusercontent.com/304450/31361605-5ec63664-ad54-11e7-9f2b-2fa9e97ef9c1.png)

And as soon as I touch it, it crashes:
![screen shot 2017-10-09 at 11 43 53 pm](https://user-images.githubusercontent.com/304450/31361557-2cdf34ac-ad54-11e7-8de5-bcc67fbc814b.png)

**Comment by Ernoff** [comment]
This is react-native-swipper? What do you suggest now?

**Comment by machour** [comment]
Obviously next step is adapting `rn-app-intro` to play well with the new updated swiper, whose API seems to have changed.

Until then, this fork have no usefulness :/

**Comment by Ernoff** [comment]
Go ahead and make a PR. I would appreciate the help
